"use client";

import { useEffect, useMemo, useState } from "react";
import { FiActivity, FiBookOpen, FiDatabase, FiRefreshCw, FiTrendingUp, FiUsers } from "react-icons/fi";

export type DashboardData = { userCount:number; deckCount:number; vocabularyCount:number; onlineCount:number; onlineUsers:Array<{id:string;username:string;displayName:string;email:string;avatarUrl:string;path:string;lastSeenAt:string}>; activity:Array<{dateKey:string;count:number}>; updatedAt:string };

export function AdminDashboardClient({initialData}:{initialData:DashboardData}) {
  const [data,setData]=useState(initialData); const [refreshing,setRefreshing]=useState(false);
  async function refresh(){setRefreshing(true);try{const response=await fetch("/api/admin/dashboard",{cache:"no-store"});const payload=await response.json() as {data?:DashboardData};if(response.ok&&payload.data)setData(payload.data);}finally{setRefreshing(false)}}
  useEffect(()=>{queueMicrotask(()=>void refresh());const timer=window.setInterval(()=>void refresh(),10_000);return()=>window.clearInterval(timer);},[]);
  const max=useMemo(()=>Math.max(1,...data.activity.map(item=>item.count)),[data.activity]);
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.28em] text-teal-700">Quản trị hệ thống</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Admin Dashboard</h1><p className="mt-3 max-w-2xl text-slate-500">Theo dõi người dùng online và hoạt động học tập theo thời gian thực.</p></div><button className="inline-flex h-12 items-center gap-2 rounded-2xl border bg-white px-4 text-sm font-black shadow-sm" onClick={()=>void refresh()} type="button"><FiRefreshCw className={refreshing?"animate-spin":""}/> Cập nhật</button></div>
    <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={FiUsers} label="Người dùng" value={data.userCount} tone="bg-rose-50 text-rose-700"/><Metric icon={FiActivity} label="Đang online" value={data.onlineCount} tone="bg-teal-50 text-teal-700" live/><Metric icon={FiBookOpen} label="Bộ từ / khóa" value={data.deckCount} tone="bg-indigo-50 text-indigo-700"/><Metric icon={FiDatabase} label="Từ vựng" value={data.vocabularyCount} tone="bg-amber-50 text-amber-700"/></div>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-sm font-black text-slate-500">Người dùng duy nhất mỗi ngày</p><h2 className="mt-1 text-2xl font-black">Hoạt động 7 ngày gần nhất</h2></div><FiTrendingUp className="h-7 w-7 text-teal-600"/></div><div className="mt-8 flex h-64 items-end gap-3">{data.activity.map(item=><div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={item.dateKey}><span className="text-xs font-black text-slate-600">{item.count}</span><div className="min-h-1 w-full rounded-t-xl bg-gradient-to-t from-teal-500 to-rose-400 transition-all" style={{height:`${Math.max(3,item.count/max*85)}%`}}/><span className="text-xs font-black text-slate-400">{new Date(`${item.dateKey}T00:00:00`).toLocaleDateString("vi-VN",{weekday:"short",day:"2-digit"})}</span></div>)}</div></div>
      <div className="rounded-[2rem] border border-slate-200 bg-slate-950 p-6 text-white shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-teal-300">Thời gian thực</p><h2 className="mt-2 text-2xl font-black">Đang online ({data.onlineCount})</h2></div><span className="relative flex h-3 w-3"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75"/><span className="relative inline-flex h-3 w-3 rounded-full bg-emerald-500"/></span></div><div className="mt-5 max-h-72 space-y-3 overflow-y-auto">{data.onlineUsers.map(user=><div className="flex items-center gap-3 rounded-2xl bg-white/8 p-3" key={user.id}><span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full bg-teal-600 font-black">{user.avatarUrl?<img alt="" className="h-full w-full object-cover" src={user.avatarUrl}/>:user.username.slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate font-black">{user.displayName||user.username}</p><p className="truncate text-xs text-slate-400">{pathLabel(user.path)}</p></div><span className="text-[11px] font-bold text-emerald-300">{secondsAgo(user.lastSeenAt)}s trước</span></div>)}{!data.onlineUsers.length&&<p className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm font-bold text-slate-400">Chưa có người dùng online.</p>}</div><p className="mt-4 text-xs text-slate-500">Tự cập nhật mỗi 10 giây · online nếu có tín hiệu trong 90 giây.</p></div></section></div>;
}
function Metric({icon:Icon,label,value,tone,live=false}:{icon:typeof FiUsers;label:string;value:number;tone:string;live?:boolean}){return <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-xl"><div className="flex justify-between"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${tone}`}><Icon className="h-6 w-6"/></span>{live&&<span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">● Live</span>}</div><p className="mt-6 text-4xl font-black">{value.toLocaleString("vi-VN")}</p><p className="mt-2 text-sm font-bold text-slate-500">{label}</p></div>}
function secondsAgo(value:string){return Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000))}
function pathLabel(path:string){if(path.startsWith("/admin"))return "Khu vực quản trị";if(path.includes("study"))return "Đang luyện tập";if(path.includes("my-vocabulary"))return "Bộ từ cá nhân";if(path.includes("discover"))return "Đang khám phá";return path||"Trang chủ"}
