"use client";
import { useEffect } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Underline from "@tiptap/extension-underline";
import { TextStyle } from "@tiptap/extension-text-style";
import Color from "@tiptap/extension-color";
import Highlight from "@tiptap/extension-highlight";
import TextAlign from "@tiptap/extension-text-align";
import { FiBold, FiCode, FiItalic, FiList, FiMinus, FiRotateCcw, FiRotateCw, FiUnderline } from "react-icons/fi";
export type RichDoc = Record<string, unknown>;
const extensions=[StarterKit,Underline,TextStyle,Color,Highlight.configure({multicolor:true}),TextAlign.configure({types:["heading","paragraph"]})];
export function RichTextEditor({content,editable=true,onChange}:{content:RichDoc;editable?:boolean;onChange?:(doc:RichDoc)=>void}){const editor=useEditor({extensions,content,editable,immediatelyRender:false,onUpdate:({editor})=>onChange?.(editor.getJSON())});useEffect(()=>{editor?.setEditable(editable)},[editable,editor]);useEffect(()=>{if(editor&&!editor.isFocused)editor.commands.setContent(content)},[content,editor]);if(!editor)return <div className="min-h-40 animate-pulse rounded-xl bg-slate-100"/>;return <div className="flex min-h-[360px] flex-row-reverse overflow-hidden rounded-xl border border-slate-200 bg-white">{editable&&<div className="flex w-12 shrink-0 flex-col items-center gap-1 overflow-y-auto border-l bg-slate-50 py-2"><Tool title="In đậm" active={editor.isActive("bold")} onClick={()=>editor.chain().focus().toggleBold().run()}><FiBold/></Tool><Tool title="In nghiêng" active={editor.isActive("italic")} onClick={()=>editor.chain().focus().toggleItalic().run()}><FiItalic/></Tool><Tool title="Gạch chân" active={editor.isActive("underline")} onClick={()=>editor.chain().focus().toggleUnderline().run()}><FiUnderline/></Tool><Tool title="Gạch ngang" onClick={()=>editor.chain().focus().toggleStrike().run()}>S</Tool>{[1,2,3].map(level=><Tool title={`Tiêu đề ${level}`} key={level} onClick={()=>editor.chain().focus().toggleHeading({level:level as 1|2|3}).run()}>H{level}</Tool>)}<Tool title="Danh sách" onClick={()=>editor.chain().focus().toggleBulletList().run()}><FiList/></Tool><Tool title="Danh sách số" onClick={()=>editor.chain().focus().toggleOrderedList().run()}>1.</Tool><Tool title="Khung nhấn mạnh" onClick={()=>editor.chain().focus().toggleBlockquote().run()}>▣</Tool><Tool title="Code" onClick={()=>editor.chain().focus().toggleCode().run()}><FiCode/></Tool><Tool title="Đường phân cách" onClick={()=>editor.chain().focus().setHorizontalRule().run()}><FiMinus/></Tool>{["left","center","right"].map(a=><Tool title={`Căn ${a}`} key={a} onClick={()=>editor.chain().focus().setTextAlign(a).run()}>{a==="left"?"←":a==="center"?"↔":"→"}</Tool>)}<label className="grid h-8 w-8 cursor-pointer place-items-center rounded-md border bg-white" title="Màu chữ"><input className="h-4 w-4" type="color" onChange={e=>editor.chain().focus().setColor(e.target.value).run()}/></label><label className="grid h-8 w-8 cursor-pointer place-items-center rounded-md border bg-amber-100" title="Màu nền"><input className="h-4 w-4" type="color" onChange={e=>editor.chain().focus().toggleHighlight({color:e.target.value}).run()}/></label><Tool title="Hoàn tác" onClick={()=>editor.chain().focus().undo().run()}><FiRotateCcw/></Tool><Tool title="Làm lại" onClick={()=>editor.chain().focus().redo().run()}><FiRotateCw/></Tool></div>}<EditorContent className="roadmap-editor min-w-0 flex-1 p-4" editor={editor}/></div>}
function Tool({active=false,children,onClick,title}:{active?:boolean;children:React.ReactNode;onClick:()=>void;title:string}){return <button aria-label={title} className={`grid h-8 w-8 shrink-0 place-items-center rounded-md border text-[11px] font-black transition ${active?"bg-slate-950 text-white":"bg-white hover:border-teal-400 hover:text-teal-700"}`} onClick={onClick} title={title} type="button">{children}</button>}
