"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { FiBookOpen, FiEdit3, FiLayers, FiPlus, FiX } from "react-icons/fi";
import { useLanguage } from "../i18n/LanguageProvider";
type Course = { _id: string; title: string; description: string; visibility: "private"|"unlisted"|"public"; lessonCount: number; completedCount: number; updatedAt: string; isOwner: boolean; ownerId?: { displayName?: string; username?: string } };
type RoadmapResponse = { data?: Course[] | { id?: string }; message?: string };


async function readRoadmapResponse(response: Response): Promise<RoadmapResponse> {
  const text = await response.text();
  if (!text.trim()) return {};

  try {
    return JSON.parse(text) as RoadmapResponse;
  } catch {
    return {};
  }
}

export function RoadmapsClient() { const router = useRouter(); const [courses,setCourses]=useState<Course[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [visibility,setVisibility]=useState<Course["visibility"]>("private");
  useEffect(()=>{ void fetch("/api/roadmaps",{cache:"no-store"}).then(async r=>{const p=await readRoadmapResponse(r);if(!r.ok)throw new Error();setCourses(Array.isArray(p.data)?p.data:[])}).catch(()=>setCourses([])).finally(()=>setLoading(false));},[]);
  async function createCourse(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/roadmaps",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description,visibility})});const p=await readRoadmapResponse(r);if(!r.ok)throw new Error(p.message||"Không thể tạo khóa học. Vui lòng thử lại.");const data=!Array.isArray(p.data)?p.data:undefined;if(!data?.id)throw new Error("Không thể tạo khóa học. Vui lòng thử lại.");router.push(`/flashcards/roadmaps/${data.id}`)}catch(e){setError(e instanceof Error?e.message:"Không thể tạo khóa học. Vui lòng thử lại.")}finally{setSaving(false)}}
  const myCourses = courses.filter((course) => course.isOwner);
  const publicCourses = courses.filter((course) => !course.isOwner && course.visibility === "public");
  return <div className="mx-auto max-w-[1500px] px-4 py-8 sm:px-6 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-4" data-scroll-reveal><div><p className="text-xs font-black uppercase tracking-[.28em] text-rose-600">Luyện tập</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Khóa học lộ trình</h1><p className="mt-3 text-slate-500">Tự xây dựng lộ trình học tiếng Nhật theo cách của bạn.</p></div><button className="flex h-12 items-center gap-2 rounded-2xl bg-rose-600 px-5 font-black text-white" onClick={()=>setOpen(true)}><FiPlus/> Tạo khóa học lộ trình</button></div>{error&&<p className="mt-5 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700" data-scroll-reveal>{error}</p>}{loading?<p className="mt-8 font-bold text-slate-500" data-scroll-reveal>Đang tải...</p>:<div className="space-y-12"><CourseSection courses={myCourses} emptyMessage="Bạn chưa có khóa học lộ trình nào." subtitle="Các lộ trình do bạn tạo và quản lý." title="Khóa học của tôi"/><CourseSection courses={publicCourses} emptyMessage="Chưa có khóa học công khai." subtitle="Khám phá các lộ trình được chia sẻ với cộng đồng." title="Khóa học công khai"/></div>}{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm"><form className="w-full max-w-xl rounded-[2rem] bg-white p-6" onSubmit={createCourse}><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-rose-600">Lộ trình mới</p><h2 className="mt-2 text-3xl font-black">Tạo khóa học lộ trình</h2></div><button type="button" onClick={()=>setOpen(false)}><FiX/></button></div><label className="mt-6 block text-sm font-black">Tên khóa lộ trình<input autoFocus required minLength={2} maxLength={120} className="mt-2 h-12 w-full rounded-2xl border px-4" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="mt-4 block text-sm font-black">Mô tả<textarea maxLength={1000} className="mt-2 min-h-24 w-full rounded-2xl border p-4" value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="mt-4 block text-sm font-black">Quyền truy cập<select className="mt-2 h-12 w-full rounded-2xl border px-4" value={visibility} onChange={e=>setVisibility(e.target.value as Course["visibility"])}><option value="private">Riêng tư · Chỉ mình tôi</option><option value="unlisted">Không công khai · Ai có link có thể xem</option><option value="public">Công khai · Mọi người có thể xem</option></select></label><div className="mt-6 flex justify-end gap-3"><button type="button" className="h-12 rounded-2xl border px-5 font-black" onClick={()=>setOpen(false)}>Hủy</button><button disabled={saving} className="h-12 rounded-2xl bg-rose-600 px-6 font-black text-white">{saving?"Đang tạo...":"Tạo và thiết lập bài"}</button></div></form></div>}</div> }
function CourseSection({courses,emptyMessage,subtitle,title}:{courses:Course[];emptyMessage:string;subtitle:string;title:string}){return <section className="mt-8"><div data-scroll-reveal><h2 className="text-2xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{courses.length?<div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3" data-scroll-reveal-stagger>{courses.map(course=><CourseCard course={course} key={course._id}/>)}</div>:<div className="mt-5 rounded-3xl border border-dashed border-slate-300 bg-white/70 p-8 text-center font-bold text-slate-500" data-scroll-reveal>{emptyMessage}</div>}</section>}
function CourseCard({course}:{course:Course}){const {translate}=useLanguage();const percent=course.lessonCount?Math.round(course.completedCount/course.lessonCount*100):0;return <article className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/[.04]" data-scroll-reveal-item><span className="grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-xl text-teal-700"><FiLayers/></span><h3 className="mt-5 text-xl font-black">{course.title}</h3><p className="mt-2 min-h-12 text-sm text-slate-500">{course.description||translate("Chưa có mô tả.")}</p><div className="mt-4 flex justify-between text-sm font-bold text-slate-600"><span>{translate(`${course.lessonCount} bài học`)}</span><span>{translate(visibilityLabel(course.visibility))}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-teal-500" style={{width:`${percent}%`}}/></div><p className="mt-2 text-xs font-bold text-slate-500">{translate(`Tiến độ ${course.completedCount}/${course.lessonCount} bài · ${percent}%`)}</p><Link className="mt-5 flex h-11 items-center justify-center gap-2 rounded-2xl bg-slate-950 font-black text-white" href={`/flashcards/roadmaps/${course._id}`}>{translate(course.completedCount?"Tiếp tục học":"Xem khóa học")} <FiBookOpen/></Link>{course.isOwner&&<Link className="mt-2 flex h-10 items-center justify-center gap-2 rounded-xl border border-teal-200 bg-teal-50 text-sm font-black text-teal-800" href={`/flashcards/roadmaps/${course._id}`}><FiEdit3/> {translate("Chỉnh sửa")}</Link>}</article>}
function visibilityLabel(v:string){return {private:"Riêng tư",unlisted:"Có link",public:"Công khai"}[v]||v}
