"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { FiCheck, FiEdit3, FiX } from "react-icons/fi";
type Question = { level: string; testNumber: number; section: "vocabularyKanji" | "grammarReading"; questionId: string; prompt: string; highlightText: string };
type Suggestion = { id: string; level: string; testNumber: number; questionId: string; prompt: string; currentHighlightText: string; suggestedHighlightText: string; note?: string; username?: string; status: "pending" | "approved" | "rejected" };

export function JlptHighlightsClient({ questions, suggestions }: Readonly<{ questions: Question[]; suggestions: Suggestion[] }>) {
 const router=useRouter(), [query,setQuery]=useState(""), [values,setValues]=useState<Record<string,string>>({}), [loading,setLoading]=useState(""), [message,setMessage]=useState("");
 const filtered=useMemo(()=>questions.filter(q=>`${q.level} ${q.testNumber} ${q.prompt}`.toLowerCase().includes(query.toLowerCase())).slice(0,100),[questions,query]);
 async function review(id:string,action:"approve"|"reject"){setLoading(id);setMessage("");const r=await fetch(`/api/admin/jlpt-highlights/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const p=await r.json();setLoading("");if(!r.ok)return setMessage(p.message||"Không thể xử lý góp ý.");router.refresh()}
 async function save(q:Question){const key=`${q.level}-${q.testNumber}-${q.section}-${q.questionId}`;setLoading(key);setMessage("");const r=await fetch("/api/admin/jlpt-highlights",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...q,highlightText:values[key]??q.highlightText})});const p=await r.json();setLoading("");if(!r.ok)return setMessage(p.message||"Không thể lưu highlight.");setMessage("Đã cập nhật highlight.");router.refresh()}
 const pending=suggestions.filter(s=>s.status==="pending");
 return <div><p className="text-xs font-black uppercase tracking-[.28em] text-teal-700">Admin · JLPT</p><h1 className="mt-3 text-4xl font-black">Quản lý highlight</h1><p className="mt-3 text-slate-500">Duyệt góp ý của người học hoặc tự chọn đoạn chữ cần highlight.</p>{message&&<p className="mt-5 rounded-xl bg-amber-50 p-4 font-bold text-amber-800">{message}</p>}
 <section className="mt-8"><h2 className="text-2xl font-black">Góp ý chờ duyệt</h2><div className="mt-4 grid gap-4">{pending.map(s=><article key={s.id} className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><b>{s.level} · Đề {s.testNumber} · {s.questionId}</b><p className="mt-2 text-lg font-black">{s.prompt}</p><p className="mt-2 text-sm text-slate-500">Người gửi: {s.username||"Người học"}{s.note?` · ${s.note}`:""}</p></div><div className="flex gap-2"><button disabled={loading===s.id} onClick={()=>review(s.id,"approve")} className="inline-flex h-10 items-center gap-2 rounded-xl bg-teal-700 px-4 font-black text-white"><FiCheck/> Duyệt</button><button disabled={loading===s.id} onClick={()=>review(s.id,"reject")} className="inline-flex h-10 items-center gap-2 rounded-xl bg-rose-600 px-4 font-black text-white"><FiX/> Từ chối</button></div></div><div className="mt-4 flex gap-3 text-sm"><span className="rounded-xl bg-slate-100 px-3 py-2">Hiện tại: <b>{s.currentHighlightText||"Không có"}</b></span><span className="rounded-xl bg-teal-50 px-3 py-2 text-teal-800">Đề xuất: <b>{s.suggestedHighlightText}</b></span></div></article>)}{!pending.length&&<p className="rounded-2xl border border-dashed p-6 text-slate-500">Không có góp ý đang chờ.</p>}</div></section>
 <section className="mt-10"><h2 className="text-2xl font-black">Chỉnh trực tiếp</h2><input value={query} onChange={e=>setQuery(e.target.value)} className="mt-4 h-12 w-full max-w-xl rounded-xl border bg-white px-4" placeholder="Tìm theo cấp độ, đề hoặc nội dung..."/><div className="mt-4 grid gap-3">{filtered.map(q=>{const key=`${q.level}-${q.testNumber}-${q.section}-${q.questionId}`;return <article key={key} className="rounded-2xl border bg-white p-4"><p className="text-xs font-black text-teal-700">{q.level} · Đề {q.testNumber} · {q.questionId}</p><p className="mt-2 font-bold">{q.prompt}</p><div className="mt-3 flex gap-2"><input value={values[key]??q.highlightText} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} className="h-11 flex-1 rounded-xl border px-3" placeholder="Để trống nếu không highlight"/><button disabled={loading===key} onClick={()=>save(q)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 font-black text-white"><FiEdit3/> Lưu</button></div></article>})}</div></section></div>;
}
