"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FiEdit3, FiExternalLink, FiPlus, FiShoppingBag, FiTrash2, FiX } from "react-icons/fi";

type Product = { _id: string; title: string; description: string; level: string; imageUrl: string; affiliateUrl: string; price?: number; originalPrice?: number; accent: "rose"|"teal"|"violet"|"amber"|"blue"; isActive: boolean; sortOrder: number };
type Form = Omit<Product, "_id">;
const emptyForm: Form = { title: "", description: "", level: "", imageUrl: "", affiliateUrl: "", price: undefined, originalPrice: undefined, accent: "rose", isActive: false, sortOrder: 0 };

export function AffiliateProductsClient({ capabilities }: { capabilities: { create: boolean; update: boolean; delete: boolean } }) {
  const [items, setItems] = useState<Product[]>([]); const [form, setForm] = useState<Form>(emptyForm); const [editing, setEditing] = useState<Product|null>(null);
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const r = await fetch("/api/admin/affiliate-products", { cache: "no-store" }); const p = await r.json(); if (r.ok) setItems(p.data || []); else setMessage(p.message || "Không thể tải sản phẩm."); }, []);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  function create() { setEditing(null); setForm(emptyForm); setMessage(""); setOpen(true); }
  function edit(item: Product) { setEditing(item); setForm({ title:item.title,description:item.description||"",level:item.level||"",imageUrl:item.imageUrl||"",affiliateUrl:item.affiliateUrl||"",price:item.price,originalPrice:item.originalPrice,accent:item.accent||"rose",isActive:item.isActive,sortOrder:item.sortOrder||0 }); setMessage(""); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); const r = await fetch(editing ? `/api/admin/affiliate-products/${editing._id}` : "/api/admin/affiliate-products", { method: editing ? "PATCH" : "POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(form) }); const p=await r.json(); setBusy(false); if(!r.ok){setMessage(p.message||"Không thể lưu sản phẩm.");return;} setOpen(false); await load(); }
  async function remove(item: Product) { if(!window.confirm(`Xóa sản phẩm “${item.title}”?`)) return; const r=await fetch(`/api/admin/affiliate-products/${item._id}`,{method:"DELETE"}); const p=await r.json(); if(!r.ok){setMessage(p.message||"Không thể xóa.");return;} await load(); }
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.24em] text-orange-600">Shopee Affiliate</p><h1 className="mt-2 text-4xl font-black">Sản phẩm cửa hàng sách</h1><p className="mt-2 text-sm font-semibold text-slate-500">Tạo sản phẩm trước, thêm link affiliate sau khi Shopee duyệt.</p></div>{capabilities.create&&<button onClick={create} className="flex h-12 items-center gap-2 rounded-2xl bg-orange-600 px-5 font-black text-white"><FiPlus/> Thêm sản phẩm</button>}</div>{message&&<p className="mt-4 rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{message}</p>}
  <div className="mt-6 grid gap-4 xl:grid-cols-2">{items.map(item=><article className="flex gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm" key={item._id}>{item.imageUrl?<img alt="" className="h-24 w-24 rounded-2xl object-cover" src={item.imageUrl}/>:<span className="grid h-24 w-24 shrink-0 place-items-center rounded-2xl bg-orange-50 text-3xl text-orange-500"><FiShoppingBag/></span>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><span className={`text-xs font-black ${item.isActive?"text-teal-600":"text-slate-400"}`}>{item.isActive?"ĐANG HIỂN THỊ":"ĐANG ẨN"}</span><h2 className="truncate text-xl font-black">{item.title}</h2></div><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-black">#{item.sortOrder}</span></div><p className="mt-1 line-clamp-2 text-sm text-slate-500">{item.description}</p><div className="mt-3 flex flex-wrap gap-2">{item.affiliateUrl&&<a className="grid h-9 w-9 place-items-center rounded-xl bg-orange-50 text-orange-600" href={item.affiliateUrl} target="_blank" rel="noopener noreferrer"><FiExternalLink/></a>}{capabilities.update&&<button className="grid h-9 w-9 place-items-center rounded-xl bg-teal-50 text-teal-700" onClick={()=>edit(item)}><FiEdit3/></button>}{capabilities.delete&&<button className="grid h-9 w-9 place-items-center rounded-xl bg-rose-50 text-rose-600" onClick={()=>void remove(item)}><FiTrash2/></button>}</div></div></article>)}{!items.length&&<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center font-bold text-slate-500">Chưa có sản phẩm. Hãy tạo sản phẩm đầu tiên.</div>}</div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/55 p-4"><form className="my-6 w-full max-w-2xl rounded-[2rem] bg-white p-6 shadow-2xl" onSubmit={save}><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-orange-600">Sản phẩm Shopee</p><h2 className="mt-1 text-2xl font-black">{editing?"Sửa sản phẩm":"Thêm sản phẩm"}</h2></div><button type="button" onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100"><FiX/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Tên sản phẩm"><input required minLength={2} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Trình độ / nhãn"><input placeholder="N5–N4" value={form.level} onChange={e=>setForm({...form,level:e.target.value})}/></Field><Field label="Giá hiện tại"><input type="number" min="0" value={form.price??""} onChange={e=>setForm({...form,price:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="Giá gốc"><input type="number" min="0" value={form.originalPrice??""} onChange={e=>setForm({...form,originalPrice:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="Link ảnh"><input type="url" placeholder="https://..." value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></Field><Field label="Link affiliate Shopee"><input type="url" placeholder="Để trống khi đang chờ duyệt" value={form.affiliateUrl} onChange={e=>setForm({...form,affiliateUrl:e.target.value})}/></Field><Field label="Màu thẻ"><select value={form.accent} onChange={e=>setForm({...form,accent:e.target.value as Form["accent"]})}><option value="rose">Đỏ cam</option><option value="teal">Xanh ngọc</option><option value="violet">Tím</option><option value="amber">Cam</option><option value="blue">Xanh dương</option></select></Field><Field label="Thứ tự"><input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)||0})}/></Field></div><Field label="Mô tả"><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><label className="mt-4 flex items-center gap-3 rounded-2xl bg-teal-50 p-4 font-black text-teal-800"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Hiển thị trên cửa hàng sách</label>{message&&<p className="mt-3 text-sm font-bold text-rose-600">{message}</p>}<button disabled={busy} className="mt-5 h-12 w-full rounded-2xl bg-slate-950 font-black text-white disabled:opacity-50">{busy?"Đang lưu...":"Lưu sản phẩm"}</button></form></div>}</div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block"><span className="mb-2 block text-sm font-black">{label}</span><span className="[&>input]:h-12 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:px-4 [&>select]:h-12 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:px-4 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:p-4">{children}</span></label>}
