import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getAuthSession, requireAuth } from "@/lib/auth/session";
import { connectMongoDB } from "@/lib/mongodb";
import { RoadmapCourseModel } from "@/models/RoadmapCourse";
import { RoadmapProgressModel } from "@/models/RoadmapProgress";
const CourseSchema = z.object({ title: z.string().trim().min(2).max(120), description: z.string().trim().max(1000).default(""), visibility: z.enum(["private", "unlisted", "public"]) });
export async function GET() { const session = await getAuthSession(); await connectMongoDB(); const filter = session ? { $or: [{ ownerId: session.userId }, { visibility: { $in: ["public", "unlisted"] } }] } : { visibility: "public" }; const courses = await RoadmapCourseModel.find(filter).populate("ownerId", "displayName username").sort({ updatedAt: -1 }).lean(); const progress = session ? await RoadmapProgressModel.find({ userId: session.userId, courseId: { $in: courses.map((c) => c._id) } }).lean() : []; const byCourse = new Map(progress.map((p) => [String(p.courseId), p])); return NextResponse.json({ data: courses.map((c) => ({ ...c, _id: String(c._id), isOwner: Boolean(session && String((c.ownerId as { _id?: unknown })?._id || c.ownerId) === session.userId), completedCount: byCourse.get(String(c._id))?.completedLessonIds?.length || 0 })) }); }
export async function POST(request: NextRequest) { const session = await requireAuth(); await connectMongoDB(); const payload = CourseSchema.parse(await request.json()); const base = payload.title.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/đ/g, "d").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "lo-trinh"; const course = await RoadmapCourseModel.create({ ...payload, ownerId: session.userId, slug: `${base}-${Date.now().toString(36)}` }); return NextResponse.json({ data: { id: String(course._id) } }, { status: 201 }); }
